name: Cfx.re Server Key Detector
author: silas-x
description: >
  Detect unintential commits of Cfx.re server keys in code

runs:
  using: 'composite'
  steps:
    - name: Install Semgrep
      run: python3 -m pip install semgrep
      shell: bash
      
      uses: actions/checkout@v4
      
    - name: Run Scan
      run: semgrep scan --config=cfx-rule.yml
      shell: bash
