name: Cfx.re Server Key Detector
author: Cfx.re
description: >
  Detect committed Cfx.re server keys in source code

runs:
  using: 'composite'
  steps:
    - name: Install Semgrep
      run: python3 -m pip --quiet install semgrep
      shell: bash
      
    - name: Key detector 🔎
      run: semgrep scan --config=${{ github.action_path }}/cfx-rule.yml --error --scan-unknown-extensions
      shell: bash
