name: Cfx.re Server Key Detector
author: Cfx.re
description: >
  Detect committed Cfx.re server keys in source code

runs:
  using: 'composite'
  steps:
    - name: Install Semgrep
      run: python3 -m pip install semgrep
      shell: bash
      
    - name: Run Scan
      run: semgrep scan --config=${{ github.action_path }}/cfx-rule.yml --error
      shell: bash
