name: Cfx.re Server Key Detector
author: silas-x
description: >
  Detect unintential commits of Cfx.re server keys in code

runs:
  using: 'docker'
  image: 'docker://returntocorp/semgrep:latest'
  run: 'semgrep ci'
